# coding=utf-8
"""
Desenvolvedor:	asantos
E-mail:			Arannã Sousa Santos
Mês:			04
Ano:			2015
Empresa:		TINS - SOLUCOES CORPORATIVAS
"""
__author__ = u'asantos'

class CODIGO_MOEDA(object):
	RESERVADO_USO_FUTURO = u'01'
	DOLAR_AMERICANO_COMERCIAL = u'02'
	DOLAR_AMERICANO_TURISMO = u'03'
	REAL = u'09'

class TIPO_REGISTRO(object):
	"""
	G003	-	registro
	"""
	ARQUIVO_HEADER = u'0'

	LOTE_HEADER = u'1'
	LOTE_INICIO = u'2'		# opcional

	SEGMENTO = u'3'

	LOTE_FINAL = u'4'		# opcional
	LOTE_TRAILER = u'5'

	ARQUIVO_TRAILER = u'9'

class TIPO_OPERACAO(object):
	"""
	G028
	"""
	LANCAMENTO_A_CREDITO = u'C'
	LANCAMENTO_A_DEBITO = u'D'
	EXTRATO_CONCILIACAO = u'E'
	EXTRATO_GESTAO_CAIXA = u'G'
	INFORMACOES_TITULO_CAPTURADOS_PROPRIO_BANCO = u'I'
	ARQUIVO_REMESSA = u'R'
	ARQUIVO_RETORNO = u'T'

class NIVEIS(object):
	N0 = 0
	N1 = 4
	N2 = 8
	N3 = 12
	N4 = 16
	N5 = 20
	N6 = 24
	N7 = 28

def gera_text(n, t):
	"""
	:param n:		Numero do nivel
	:param t: 		Texto para informar no nivel
	:return:
	"""
	return u'%s %s' % (u'-' * n, t)

# ----------------------------------------------------------
# 	CODIGOS
# ----------------------------------------------------------
class G005(object):
	descricao = u'Tipo de inscrição da empresa'
	ISENTO_NAO_INFORMADO = u'0'
	CPF = u'1'
	CGC_CNPJ = u'2'
	PIS_PASEP = u'3'
	OUTROS = u'9'

class G015(object):
	descricao = u'código remessa/retorno'
	REMESSA =  u'1'			# cliente -> banco
	RETORNO = u'2'			# banco -> cliente

class C039(object):
	descricao = u'Aviso para débito automático'

	EMITE_AVISO_COM_ENDERECO_INFORMADO_NO_ARQUIVO_REMESSA = u'01'
	NAO_EMITE_AVISO = u'02'
	EMITE_AVISO_COM_ENDERECO_CONSTANTE_DO_CADASTRO_DO_BANCO = u'03'		# default

class C004(object):
	descricao = u'Código de movimento remessa'

	ENTRADA_TITULOS = U'01'
	PEDIDO_BAIXA = U'02'
	ABATIMENTO_CONCESSAO = u'04'
	ABATIMENTO_CANCELAMENTO = U'05'
	ALTERACAO_VENCIMENTO = U'06'
	DESCONTO_CONCESSAO = U'07'
	DESCONTO_CANCELAMENTO = U'08'
	PROTESTAR = U'09'
	CANCELA_SUSTENTACAO_INSTRUCAO_PROTESTO = U'10'
	RECUSA_DA_ALEGACAO_SACADO = U'30'
	ALTERACAO_OUTROS_DADOS = U'31'
	ALTERACAO_MODALIDADE = U'40'

class C006(object):
	descricao = u'Código da carteira'

	COBRANCA_SIMPLES = U'1'
	COBRANCA_VINCULADA = U'2'
	COBRANCA_CAUCIONADA = U'3'
	COBRANCA_DESCONTADA = U'4'
	COBRANCA_VENDOR = U'5'


class C040(object):
	descricao = u'Tipo de impressão'

	FRENTE_DO_BLOQUETO = u'1'
	VERSO_DO_BLOQUETO = u'2'
	CORPO_INSTRUCAO_FICHA_COMPENSASAO_BLOQUETO = u'3'

class C041(object):
	descricao = u'Número da linha a ser impressa'

	FRENTE_BLOQUETO = [unicode(x).zfill(2) for x in range(1, 36 + 1)]
	VERSO_BLOQUETO = [unicode(x).zfill(2) for x in range(1, 24 + 1)]

class C043(object):
	descricao = u'Tipo do caracter a ser impresso'

	NORMAL = u'01'
	ITALICO = u'02'
	NORMAL_NEGRITO = u'03'
	ITALICO_NEGRITO = u'04'

class C044(object):
	descricao = u'Código de movimento retorno'

	ENTRADA_CONFIRMADA = u'02'
	ENTRADA_REJEITADA = u'03'
	TRANSFERENCIA_CARTEIRA_ENTRADA = u'04'
	TRANSFERENCIA_CARTEIRA_BAIXA = u'05'
	LIQUIDACAO = u'06'
	CONFIRMACAO_RECEBIMENTO_INSTRUCAO_DESCONTO = u'07'
	CONFIRMACAO_RECEBIMENTO_CANCELAMENTO_DESCONTO = u'08'
	BAIXA = u'09'
	TITULO_EM_CARTEIRA = u'11'
	CONFIRMACAO_RECEBIMENTO_INSTRUCAO_ABATIMENTO = u'12'
	CONFIRMACAO_RECEBIMENTO_CANCELAMENTO_ABATIMENTO = u'13'
	CONFIRMACAO_RECEBIMENTO_ALTERACAO_VENCIMENTO = u'14'

	LIQUIDACAO_APOS_BAIXA_OU_LIQUIDACAO_TITULO_NAO_REGISTRADO = u'17'
	CONFIRMACAO_RECEBIMENTO_INSTRUCAO_PROTESTO = u'19'
	CONFIRMACAO_RECEBIMENTO_INSTRUCAO_SUSTACAO_CANCELAMENTO_PROTESTO = u'20'

	REMESSA_CARTORIO = u'23'
	RETIRADA_CARTORIO_MANUTENCAO_CARTEIRA = u'24'
	PROTESTADO_E_BAIXADO = u'25'
	INSTRUCAO_REJEITADA = u'26'
	CONFIRMACAO_PEDIDO_ALTERACAO_OUTROS_DADOS = u'27'
	DEBITO_TARIFAS_CUSTAS = u'28'
	OCORRENCIA_SACADO = u'29'
	ALTERACAO_DADOS_REJEITADA = u'30'
	CONFIRMACAO_ALTERACAO_DADOS_RATEIO_CREDITO = u'33'
	CONFIRMACAO_CANCELAMENTO_DADOS_RATEIO_CREDITO = u'34'
	CONFIRMACAO_DESAGENDAMENTO_DEBITO_AUTOMATICO = u'35'

	TITULO_PAGO_COM_CHEQUE_DEVOLVIDO = u'44'
	TITULO_PAGO_COM_CHEQUE_COMPENSADO = u'45'
	CONFIRMACAO_INSTRUCAO_TRANSFERENCIA_CARTEIRA_MODALIDADE_COBRANCA = u'48'
	TITULO_PAGO_COM_CHEQUE_PENDENTE_LIQUIDACAO = u'50'
	TITULO_DDA_RECONHECIDO_PELO_SACADO = u'51'
	TITULO_DDA_NAO_RECONHECIDO_PELO_SACADO = u'52'
	TITULO_DDA_RECUSADO_PELA_CIP = u'53'

	choices = (
		(ENTRADA_CONFIRMADA, u'ENTRADA CONFIRMADA'),
		(ENTRADA_REJEITADA, u'ENTRADA REJEITADA'),
		(TRANSFERENCIA_CARTEIRA_ENTRADA, u'TRANSFERÊNCIA DE CARTEIRA/ENTRADA'),
		(TRANSFERENCIA_CARTEIRA_BAIXA, u'TRANSFERÊNCIA DE CARTEIRA/BAIXA'),
		(LIQUIDACAO, u'LIQUIDAÇÃO'),
		(CONFIRMACAO_RECEBIMENTO_INSTRUCAO_DESCONTO, u'CONFIRMAÇÃO DO RECEBIMENTO DA INSTRUÇÃO DE DESCONTO'),
		(CONFIRMACAO_RECEBIMENTO_CANCELAMENTO_DESCONTO, u'CONFIRMAÇÃO DO RECEBIMENTO DO CANCELAMENTO DO DESCONTO'),
		(BAIXA, u'BAIXA'),
		(TITULO_EM_CARTEIRA, u'TÍTULOS EM CARTEIRA (EM SER)'),
		(CONFIRMACAO_RECEBIMENTO_INSTRUCAO_ABATIMENTO, u'CONFIRMAÇÃO RECEBIMENTO INSTRUÇÃO DE ABATIMENTO'),
		(CONFIRMACAO_RECEBIMENTO_CANCELAMENTO_ABATIMENTO, u'CONFIRMAÇÃO RECEBIMENTO INSTRUÇÃO DE CANCELAMENTO ABATIMENTO'),
		(CONFIRMACAO_RECEBIMENTO_ALTERACAO_VENCIMENTO, u'CONFIRMAÇÃO RECEBIMENTO ALTERAÇÃO DE VENCIMENTO'),
		(LIQUIDACAO_APOS_BAIXA_OU_LIQUIDACAO_TITULO_NAO_REGISTRADO, u'LIQUIDAÇÃO APÓS BAIXA OU LIQUIDAÇÃO TÍTULO NÃO REGISTRADO'),
		(CONFIRMACAO_RECEBIMENTO_INSTRUCAO_PROTESTO, u'CONFIRMAÇÃO RECEBIMENTO INSTRUÇÃO DE PROTESTO'),
		(CONFIRMACAO_RECEBIMENTO_INSTRUCAO_SUSTACAO_CANCELAMENTO_PROTESTO, u'CONFIRMAÇÃO RECEBIMENTO INSTRUÇÃO DE SUSTAÇÃO/CANCELAMENTO DE PROTESTO'),
		(REMESSA_CARTORIO, u'REMESSA A CARTÓRIO (APONTE EM CARTÓRIO)'),
		(RETIRADA_CARTORIO_MANUTENCAO_CARTEIRA, u'RETIRADA DE CARTÓRIO EM MANUTENÇÃO EM CARTEIRA'),
		(PROTESTADO_E_BAIXADO, u'PROTESTADO E BAIXADO'),
		(INSTRUCAO_REJEITADA, u'INSTRUÇÃO REJEITADA'),
		(CONFIRMACAO_PEDIDO_ALTERACAO_OUTROS_DADOS, u'CONFIRMAÇÃO DO PEDIDO DE ALTERAÇÃO DE OUTROS DADOS'),
		(DEBITO_TARIFAS_CUSTAS, u'DÉBITO DE TARIFAS/CUSTAS'),
		(OCORRENCIA_SACADO, u'OCORRÊNCIAS DO SACADO'),
		(ALTERACAO_DADOS_REJEITADA, u'ALTERAÇÃO DE DADOS REJEITADA'),
		(CONFIRMACAO_ALTERACAO_DADOS_RATEIO_CREDITO, u'CONFIRMAÇÃO DA ALTERAÇÃO DOS DADOS DO RATEIO DE CRÉDITO'),
		(CONFIRMACAO_CANCELAMENTO_DADOS_RATEIO_CREDITO, u'CONFIRMAÇÃO DO CANCELAMENTO DOS DADOS DO RATEIO DE CRÉDITO'),
		(CONFIRMACAO_DESAGENDAMENTO_DEBITO_AUTOMATICO, u'CONFIRMAÇÃO DO DESAGENDAMENTO DO DÉBITO AUTOMÁTICO'),
		(TITULO_PAGO_COM_CHEQUE_DEVOLVIDO, u'TÍTULO PAGO COM CHEQUE DEVOLVIDO'),
		(TITULO_PAGO_COM_CHEQUE_COMPENSADO, u'TÍTULO PAGO COM CHEQUE COMPENSADO'),
		(CONFIRMACAO_INSTRUCAO_TRANSFERENCIA_CARTEIRA_MODALIDADE_COBRANCA, u'CONFIRMAÇÃO DE INSTRUÇÃO DE TRANSFERÊNCIA DE CARTEIRA/MODALIDADE DE COBRANÇA'),
		(TITULO_PAGO_COM_CHEQUE_PENDENTE_LIQUIDACAO, u'TÍTULO PAGO COM CHEQUE PENDENTE DE LIQUIDAÇÃO'),
		(TITULO_DDA_RECONHECIDO_PELO_SACADO, u'TÍTULO DDA RECONHECIDO PELO SACADO'),
		(TITULO_DDA_NAO_RECONHECIDO_PELO_SACADO, u'TÍTULO DDA NÃO RECONHECIDO PELO SACADO'),
		(TITULO_DDA_RECUSADO_PELA_CIP, u'TÍTULO DDA RECUSADO PELA CIP'),
	)

class C047(object):
	"""
	Complicadissimo, depende do 44 e possui 5 duplas, ou seja, até 5 erros juntos no mesmo campo
	"""
	descricao = u'Identificação para Rejeições, Tarifas, Custas, Liquidação e Baixas'

	class D_A(object):
		"""
		Domínio A

		'01' a '95' -> C044 '02', '03' ,'26' e '30'
		"""
		choices = (
			(u'01', u'CÓDIGO DO BANCO INVÁLIDO'),
			(u'02', u'CÓDIGO DO REGISTRO DETALHE INVÁLIDO'),
			(u'03', u'CÓDIGO DO SEGMENTO INVÁLIDO'),
			(u'04', u'CÓDIGO DE MOVIMENTO NÃO PERMITIDO PARA CARTEIRA'),
			(u'05', u'CÓDIGO DE MOVIMENTO INVÁLIDO'),
			(u'06', u'TIPO/NÚMERO DE INSCRIÇÃO DO CEDENTE INVÁLIDOS'),
			(u'07', u'AGÊNCIA/CONTA/DV INVÁLIDO'),
			(u'08', u'NOSSO NÚMERO INVÁLIDO'),
			(u'09', u'NOSSO NÚMERO DUPLICADO'),
			(u'10', u'CARTEIRA INVÁLIDA'),
			(u'11', u'FORMA DE CADASTRAMENTO DO TÍTULO INVÁLIDO'),
			(u'12', u'TIPO DE DOCUMENTO INVÁLIDO'),
			(u'13', u'IDENTIFICAÇÃO DA EMISSÃO DO BLOQUETO INVÁLIDA'),
			(u'14', u'IDENTIFICAÇÃO DA DISTRIBUIÇÃO DO BLOQUETO INVÁLIDA'),
			(u'15', u'CARACTERÍSTICAS DA COBRANÇA INCOMPATÍVEIS'),
			(u'16', u'DATA DE VENCIMENTO INVÁLIDA'),
			(u'17', u'DATA DE VENCIMENTO ANTERIOR A DATA DE EMISSÃO'),
			(u'18', u'VENCIMENTO FORA DO PRAZO DE OPERAÇÃO'),
			(u'19', u'TÍTULO A CARGO DE BANCOS CORRESPONDENTES COM VENCIMENTO INFERIOR A XX DIAS'),
			(u'20', u'VALOR DO TÍTULO INVÁLIDO'),
			(u'21', u'ESPÉCIE DO TÍTULO INVÁLIDA'),
			(u'22', u'ESPÉCIE DO T´TITULO NÃO PERMITIDA PARA A CARTEIRA'),
			(u'23', u'ACEITE INVÁLIDO'),
			(u'24', u'DATA DA EMISSÃO INVÁLIDA'),
			(u'25', u'DATA DE EMISSÃO POSTERIOR A DATA DE ENTRADA'),
			(u'26', u'CÓDIGO DE JUROS DE MORA INVÁLIDO'),
			(u'27', u'VALOR/TAXA DE JUROS DE MORA INVÁLIDO'),
			(u'28', u'CÓDIGO DE DESCONTO INVÁLIDO'),
			(u'29', u'VALOR DO DESCONTO MAIOR OU IGUAL AO VALOR DO TÍTULO'),
			(u'30', u'DESCONTO A CONCEDER NÃO CONFERE'),
			(u'31', u'CONCESSÃO DE DESCONTO - JÁ EXISTE DESCONTO ANTERIOR'),
			(u'32', u'VALOR DO IOF INVÁLIDO'),
			(u'33', u'VALOR DO ABATIMENTO INVÁLIDO'),
			(u'34', u'VALOR DO ABATIMENTO MIOR OU IGUAL AO VALOR DO TÍTULO'),
			(u'35', u'VALOR A CONCEDER NÃO CONFERE'),
			(u'36', u'CONCESSÃO DE ABATIMENTO - JÁ EXISTE ABATIMENTO ANTERIOR'),
			(u'37', u'CÓDIGO PARA PROTESTO INVÁLIDO'),
			(u'38', u'PRAZO PARA PROTESTO INVÁLIDO'),
			(u'39', u'PEDIDO DE PROTESTO NÃO PERMITIDO PARA O TÍTULO'),
			(u'40', u'TÍTULO COM ORDEM DE PROTESTO EMITIDA'),
			(u'41', u'PEDIDO DE CANCELAMENTO/SUSTAÇÃO PARA TÍTULOS SEM INSTRUÇÃO DE PROTESTO'),
			(u'42', u'CÓDIGO PARA BAIXA/DEVOLUÇÃO INVÁLIDO'),
			(u'43', u'PRAZO PARA BAIXA/DEVOLUÇÃO INVÁLIDO'),
			(u'44', u'CÓDIGO DA MOEDA INVÁLIDO'),
			(u'45', u'NOME DO SACADO NÃO INFOMRADO'),
			(u'46', u'TIPO/NÚMERO DE INSCRIÇÃO DO SACADO INVÁLIDO'),
			(u'47', u'ENDEREÇO DO SACADO NÃO INFORMADO'),
			(u'48', u'CEP INVÁLIDO'),
			(u'49', u'CEP SEM PRAÇA DE COBRANÇA (NÃO LOCALIZADO)'),
			(u'50', u'CEP REFERENTE A UM BANCO CORRESPONDENTE'),
			(u'51', u'CEP INCOMPATÍVEL COM A UNIDADE DA FEDERAÇÃO'),
			(u'52', u'UNIDADE DA FEDERAÇÃO INVÁLIDA'),
			(u'53', u'TIPO/NÚMERO DE INSCRIÇÃO DO SACADOR/AVALISTA INVÁLIDOS'),
			(u'54', u'SACADOR/AVALISTA NÃO INFORMADO'),
			(u'55', u'NOSSO NÚMERO NO BANCO CORRESPONDENTE NÃO INFORMADO'),
			(u'56', u'CÓDIGO DO BANCO CORRESPONDENTE NÃO INFORMADO'),
			(u'57', u'CÓDIGO DA MULTA INVÁLIDO'),
			(u'58', u'DATA DA MULTA INVÁLIDA'),
			(u'59', u'VALOR/PERCENTUAL DA MULTA INVÁLIDO'),
			(u'60', u'MOVIMENTO PARA TÍTULO NÃO CADASTRADO'),
			(u'61', u'ALTERAÇÃO DA AGÊNCIA COBRADORA/DV INVÁLIDA'),
			(u'62', u'TIPO DE IMPRESSÃO INVÁLIDO'),
			(u'63', u'ENTRADA PARA TÍTULO JÁ CADASTRADO'),
			(u'64', u'NÚMERO DA LINHA INVÁLIDO'),
			(u'65', u'CÓDIGO DO BANCO PARA DÉBITO INVÁLIDO'),
			(u'66', u'AGÊNCIA/CONTA/DV PARA DÉBITO INVÁLIDO'),
			(u'67', u'DADOS PARA DÉBITO INCOMPATÍVEL COM A IDENTIFICAÇÃO DA EMISSÃO DO BLOQUETO'),
			(u'68', u'DÉBITO AUTOMÁTICO AGENDADO'),
			(u'69', u'DÉBITO NÃO AGENDADO - ERRO NOS DADOS DA REMESSA'),
			(u'70', u'DÉBITO NÃO AGENDADO - SACADO NÃO CONSTA DO CADASTRO DE AUTORIZANTE'),
			(u'71', u'DÉBITO NÃO AGENDADO - CEDENTE NÃO AUTORIZADO PELO SACADO'),
			(u'72', u'DÉBITO NÃO AGENDADO - CEDENTE NÃO PARTICIPA DA MODALIDADE DÉBITO AUTOMÁTICO'),
			(u'73', u'DÉBITO NÃO AGENDADO - CÓDIGO DE MOEDA DIFERENTE DE REAL (R$)'),
			(u'74', u'DÉBITO NÃO AGENDADO - DATA VENCIMENTO INVÁLIDA'),
			(u'75', u'DÉBITO NÃO AGENDADO, CONFORME SEU PEDIDO, TÍTULO NÃO REGISTRADO'),
			(u'76', u'DÉBITO NÃO AGENDADO, TIPO/NUM. INSCRIÇÃO DO DEBITADO, INVÁLIDO'),
			(u'77', u'TRANSFERÊNCIA PARA DESCONTO NÃO PERMITIDA PARA A CARTEIRA DO TÍTULO'),
			(u'78', u'DATA INFERIOR OU IGUAL AO VENCIMENTO PARA DÉBITO AUTOMÁTICO'),
			(u'79', u'DATA JUROS DE MORA INVÁLIDO'),
			(u'80', u'DATA DO DESCONTO INVÁLIDA'),
			(u'81', u'TENTATIVAS DE DÉBITO ESGOTADAS - BAIXADO'),
			(u'82', u'TENTATIVAS DE DÉBITO ESGOTADAS - PENDENTE'),
			(u'83', u'LIMITE EXCEDIDO'),
			(u'84', u'NÚMERO AUTORIZAÇÃO INEXISTENTE'),
			(u'85', u'TÍTULO COM PAGAMENTO VINCULADO'),
			(u'86', u'SEU NÚMERO INVÁLIDA'),
			(u'87', u'E-MAIL/SMS ENVIADO'),
			(u'88', u'E-MAIL LIDO'),
			(u'89', u'E-MAIL/SMS DEVOLVIDO - ENDEREÇO DE E-MAIL OU NÚMERO DO CELULAR INCORRETO'),
			(u'90', u'E-MAIL DEVOLVIDO - CAIXA POSTAL CHEIA'),
			(u'91', u'E-MAIL/NÚMERO DO CELULAR DO SACADO NÃO INFORMADO'),
			(u'92', u'SACADO OPTANTE POR BLOQUETO ELETRÔNICO - E-MAIL NÃO ENVIADO'),
			(u'93', u'CÓDIGO PARA EMISSÃO DE BLOQUETO NÃO PERMITE ENVIO DE E-MAIL'),
			(u'94', u'CÓDIGO DA CARTEIRA INVÁLIDO PARA ENVIO E-MAIL'),
			(u'95', u'CONTRATO NÃO PERMITE O ENVIO DE E-MAIL'),
			(u'96', u'NÚMERO DE CONTRATO INVÁLIDO'),
			(u'97', u'REJEIÇÃO DA ALTERAÇÃO DO PRAZO LIMITE DE RECEBIMENTO'),	# (A DATA DEVE SER INFORMADA NO CAMPO 28.3.P)
			(u'98', u'REJEIÇÃO DE DISPENSA DE PRAZO LIMITE DE RECEBIMENTO'),
			(u'99', u'REJEIÇÃO DA ALTERAÇÃO DO NÚMERO DO TÍTULO DADO PELO CEDENTE'),
			(u'A1', u'REJEIÇÃO DA ALTERAÇÃO DO NÚMERO CONTROLE DO PARTICIPANTE'),
			(u'A2', u'REJEIÇÃO DA ALTERAÇÃO DOS DADOS DO SACADO'),
			(u'A3', u'REJEIÇÃO DA ATERAÇÃO DOS DADOS DO SACADOR/AVALISTA'),
			(u'A4', u'SACADO DDA'),
			(u'A5', u'REGISTRO REJEITADO - TÍTULO JÁ LIQUIDADO'),
			(u'A6', u'CÓDIGO DO CONVENENTE INVÁLIDO OU ENCERRADO'),
			(u'A7', u'TÍTULO JÁ SE ENCONTRA NA SITUAÇÃO PRETENDIDA'),
			(u'A8', u'VALOR DO ABATIMENTO INVÁLIDO PARA CANCELAMENTO'),
			(u'A9', u'NÃO AUTORIZA PAGAMENTO PARCIAL'),
			(u'B1', u'AUTORIZA RECEBIMENTO PARCIAL'),
		)

	class D_B(object):
		"""
		Domínio B
		'01' a '20' para C044 com valor '28'
		"""
		choices = (
			(u'01', u'TARIFA DE EXTRATO DE POSIÇÃO'),
			(u'02', u'TARIFA DE MANUTENÇÃO DE TÍTULO VENCIDO'),
			(u'03', u'TARIFA DE SUSTAÇÃO'),
			(u'04', u'TARIFA DE PROTESTO'),
			(u'05', u'TARIFA DE OUTRAS INSTRUÇÕES'),
			(u'06', u'TARIFA DE OUTRAS OCORRÊNCIAS'),
			(u'07', u'TARIFA DE ENVIO DE DUPLICATA AO SACADO'),
			(u'08', u'CUSTAS DE PROTESTO'),
			(u'09', u'CUSTAS DE SUSTAÇÃO DE PROTESTO'),
			(u'10', u'CUSTAS DE CARTÓRIO DISTRIBUIDOR'),
			(u'11', u'CUSTAS DE EDITAL'),
			(u'12', u'TARIFA SOBRE DEVOLUÇÃO DE TÍTULO VENCIDO'),
			(u'13', u'TARIFA SOBRE REGISTRO COBRADA NA BAIXA/LIQUIDAÇÃO'),
			(u'14', u'TARIFA SOBRE REAPRESENTAÇÃO AUTOMÁTICA'),
			(u'15', u'TARIFA SOBRE RATEIO DE CRÉDITO'),
			(u'16', u'TARIFA SOBRE INFORMAÇÕES VIA FAX'),
			(u'17', u'TARIFA SOBRE PRORROGAÇÃO DE VENCIMENTO'),
			(u'18', u'TARIFA SOBRE ALTERAÇÃO DE ABATIMENTO/DESCONTO'),
			(u'19', u'TARIFA SOBRE ARQUIVO MENSAL (EM SER)'),
			(u'20', u'TARIFA SOBRE EMISSÃO DE BLOQUETO PRÉ-EMITIDO PELO BANCO'),
		)

	class D_C(object):
		"""
		Domínio C
		'01' a '15' -> C044 '06', '09' e '17'
		"""
		choices = (
			(u'01', u'POR SALDO'),											# liquidação
			(u'02', u'POR CONTA'),
			(u'03', u'LIQUIDAÇÃO NO GUICHÊ DE CAIXA EM DINHEIRO'),
			(u'04', u'COMPENSAÇÃO ELETRÔNICA'),
			(u'05', u'COMPENSAÇÃO CONVENCIONAL'),
			(u'06', u'POR MEIO ELETRÔNICO'),
			(u'07', u'APÓS FERIADO LOCAL'),
			(u'08', u'EM CARTÓRIO'),
			(u'09', u'COMANDADA BANCO'),									# baixa
			(u'10', u'COMANDADA CLIENTE ARQUIVO'),
			(u'11', u'COMANDADA CLIENTE ON-LINE'),
			(u'12', u'DECURSO PRAZO - CLIENTE'),
			(u'13', u'DECURSO PRAZO - BANCO'),
			(u'14', u'PROTESTADO'),
			(u'15', u'TÍTULO EXCLUÍDO'),
			(u'30', u'LIQUIDAÇÃO NO GUICHÊ DE CAIXA EM CHEQUE'),			# liquidação
			(u'31', u'LIQUIDAÇÃO EM BANCO CORRESPONDENTE'),
			(u'32', u'LIQUIDAÇÃO TERMIANL DE AUTO-ATENDIMENTO'),
			(u'33', u'LIQUIDAÇÃO NA INTERNET (HOME BANKING)'),
			(u'34', u'LIQUIDADO OFFICE BANKING'),
			(u'35', u'LIQUIDADO CORRESPONDENTE EM DINHEIRO'),
			(u'36', u'LIQUIDADO CORRESONDENTE EM CHEQUE'),
			(u'37', u'LIQUIDADO POR MEIO DE CENTRAL DE ATENDIMENTO (TELEFONE)'),
		)

	def choicesBy(self, c044, valor):
		"""
		Apenas 2 digitos por vez

		"""
		c044 = unicode(valor).zfill(2)

		assert len(c044) is 2, u'Informar apenas 2 dígitos em VALOR'

		# -------------------------------------------------------
		# 	excecao 1
		# 	domínio C - liquidação/baixas - c044 '06', '09' e '17'
		# -------------------------------------------------------
		if valor in (
				C044.LIQUIDACAO,
				C044.BAIXA,
				C044.LIQUIDACAO_APOS_BAIXA_OU_LIQUIDACAO_TITULO_NAO_REGISTRADO
			):
			return dict(self.D_C.choices).get(valor, None)

		# -------------------------------------------------------
		# 	excecao 2
		# 	domínio B - tarifas/custas - c044 '28'
		# -------------------------------------------------------
		elif valor is C044.DEBITO_TARIFAS_CUSTAS:
			return dict(self.D_B.choices).get(valor, None)


		# -------------------------------------------------------
		# 	excecao 3
		# 	domínio A - rejeições
		# -------------------------------------------------------
		return dict(self.D_A.choices).get(valor, None)


class C061(object):
	descricao = u'Código de cálculo de rateio para beneficiário'

	VALOR_COBRADO = u'1'
	VALOR_REGISTRO = u'2'
	RATEIO_PELO_MENOR_VALOR = u'3'

class C062(object):
	descricao = u'Tipo de valor informado (usado na C074)'

	PERCENTUAL = u'1'
	VALOR_OU_QUANTIDADE = u'2'